app:
  initial-admin:
    email: ${BD_INITIAL_ADMIN_EMAIL:root@biblionode.com}
    password: ${BD_INITIAL_ADMIN_PASSWORD:root1234}
  rsa:
    public-key: ${RSA_PUBLIC_KEY:file:./certs/public_key.pem}
    private-key: ${RSA_PRIVATE_KEY:file:./certs/private_key.pem}

spring:
  application:
    name: BiblioNode

  datasource:
    url: jdbc:postgresql://localhost:5432/biblionode-db
    username: dev_user
    password: dev_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080

